let $tabBar = $('#app2 .tab-bar')
let $tabContent = $('#app2 .tab-content')
$tabBar.on('click', 'li', (e)=>{
    let $li = $(e.currentTarget)
    $li.addClass('color').siblings().removeClass('color')
    let index = $li.index()
    $tabContent.children()
    .eq(index).addClass('active')
    .siblings().removeClass('active')
})
